[package]
name = "exam"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1.19.0",features = ["v4"] }
anyhow = "1.0.100"
tracing = "0.1.43"
tracing-subscriber = "0.3.22"
rand = "0.9.2"
sqlx = "0.8.6"
serde = { version = "1.0", features = ["derive"] }